channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - protobuf
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pygame
    - moviepy
    - tqdm
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - expecttest
    - pyyaml
    - scipy
    - hydra-core
    - tensorboard
    - imageio==2.26.0
    - wandb
    - dm_control
    - mlflow
    - av
    - coverage
    - ray
    - virtualenv
