channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - swig
  - pip:
    - cloudpickle
    - gym
    - gym-notices
    - importlib_metadata
    - six
    - zipp
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-error-for-skips
    - expecttest
    - pyyaml
    - autorom[accept-rom-license]
    - pettingzoo[all]==1.24.3
