# by default we map the double-prec tensors to single-prec
_target_: torchrl.envs.TransformedEnv
env:
  _target_: torchrl.envs.libs.dm_control.DMControlEnv
  env_name: cheetah
  task_name: run
  frame_skip: 2
  from_pixels: True
transform:
  _target_: torchrl.envs.transforms.DoubleToFloat
  keys_in: ["action", "reward"]
  keys_inv_in: ["action"]
