channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - procgen
    - gymnasium
    - ale-py
    - pygame
    - imageio
    - matplotlib
    - numpy
    - setuptools
    - pyglet
    - pillow
    - opencv
    - tensordict
    - pytest
    - pytest-xdist
