channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - protobuf
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pygame
    - moviepy<2.0.0
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-error-for-skips
    - pytest-asyncio
    - expecttest
    - pyyaml
    - scipy
    - dm_control
    - mujoco
    - coverage
