channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-error-for-skips
    - pytest-rerunfailures
    - pytest-json-report
    - pytest-asyncio
    - expecttest
    - pybind11[global]
    - pyyaml
    - scipy==1.9.1
    - hydra-core
    - ninja
