channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - ninja
  - cmake >= 3.18
  - protobuf
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - gym_retro
    - gym
    - pygame
    - gym[accept-rom-license]
    - gym[atari]
    - moviepy
    - tqdm
    - pytest
    - pytest-cov
    - pytest-mock
    - expecttest
    - pyyaml
    - scipy
    - dm_control
    - mujoco_py
    - hydra-core
