channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - expecttest
    - pyyaml
    - scipy
    - coverage
