channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - protobuf
  - pip:
    # Initial version is required to install Atari ROMS in setup_env.sh
    - gymnasium<1.0
    - hypothesis
    - future
    - cloudpickle
    - pygame
    - moviepy<2.0.0
    - tqdm
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-error-for-skips
    - pytest-asyncio
    - expecttest
    - pyyaml
    - scipy
    - hydra-core
    - patchelf
    - mujoco==2.3.3
    - dm_control==1.0.11
    - numpy<2.0.0
