channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - protobuf
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - gym[atari]==0.13
    - pygame
    - moviepy<2.0.0
    - tqdm
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - expecttest
    - pyyaml
    - scipy
    - hydra-core
    - mujoco
    - patchelf
    - pyopengl==3.1.4
    - pyglet<1.5.0
    - ray
    - av
    - h5py
