channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - cloudpickle
    - torch
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-error-for-skips
    - pytest-asyncio
    - expecttest
