defaults:
  - collector: sync_single
  - env: cheetah
  - transforms: state
  - replay_buffer: prioritized
  - model: ddpg/basic
  - network: ddpg/state
  - exploration: linear
  - loss: ddpg_loss
  - logger: csv
num_workers: 0
