wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.21
    code_path: code/examples/dreamer/dreamer.py
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1660063763
    t:
      1:
      - 1
      - 41
      - 50
      - 55
      2:
      - 1
      - 41
      - 50
      - 55
      3:
      - 13
      4: 3.9.12
      5: 0.12.21
      8:
      - 4
      - 5
