channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-json-report
    - pytest-error-for-skips
    - pytest-asyncio
    - expecttest
    - pybind11[global]
    - pyyaml
    - scipy
    - hydra-core
    - jax[cuda12]>=0.7.0
    - brax
    - psutil
