envs: [
    AirRaid,
    Alien,
    Amidar,
    Assault,
    Asterix,
    Asteroids,
    Atlantis,
    BankHeist,
    BattleZone,
    BeamRider,
    Berzerk,
    Bowling,
    Boxing,
    Breakout,
    Carnival,
    Centipede,
    ChopperCommand,
    CrazyClimber,
    DemonAttack,
    DoubleDunk,
    ElevatorAction,
    Enduro,
    FishingDerby,
    Freeway,
    Frostbite,
    Gopher,
    Gravitar,
    IceHockey,
    Jamesbond,
    JourneyEscape,
    Kangaroo,
    Krull,
    KungFuMaster,
    MontezumaRevenge,
    MsPacman,
    NameThisGame,
    Phoenix,
    Pitfall,
    Pong,
    Pooyan,
    PrivateEye,
    Qbert,
    Riverraid,
    RoadRunner,
    Robotank,
    Skiing,
    Solaris,
    SpaceInvaders,
    StarGunner,
    Tennis,
    TimePilot,
    Tutankham,
    UpNDown,
    Venture,
    VideoPinball,
    WizardOfWor,
    YarsRevenge,
    Zaxxon
]
version: v0