# @package _global_
train:
  # Mode-specific setting
  sync: true  # Force synchronous mode
  
  # Number of epochs to train for, every time a batch is collected.
  epochs: 1
  # Leave buffer_size empty to use steps_per_batch in sync mode
  buffer_size:
  # Update policy weights every N steps - must be left empty in sync mode
  weight_update_frequency:  
