channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-error-for-skips
    - pytest-asyncio
    - expecttest
    - pybind11[global]
    - pyyaml
    - scipy
    - hydra-core
    - minari[gcs,hdf5,hf]
    - gymnasium>=1.2.0
    - ale-py
    - gymnasium-robotics
    - minari[create]
    - jax>=0.7.0
    - mujoco<3.3.6      
    - mujoco-py<2.2,>=2.1
    - minigrid
