channels:
  - pytorch
  - defaults
dependencies:
  - pip
  - pip:
    - hypothesis
    - future
    - cloudpickle
    - pytest
    - pytest-cov
    - pytest-mock
    - pytest-instafail
    - pytest-rerunfailures
    - pytest-error-for-skips
    - pytest-asyncio
    - expecttest
    - pyyaml
    - scipy
    - hydra-core
    - minari[gcs,hdf5,hf]
    - gymnasium<1.0.0
